### ISSUE TITLE
You can not store python lists in the environment

### ISSUE THREAD

**Issue by jmz-b** [UoW-CPC/Asclepios-Server#5]
In the `.env` file in this project, you define `ALLOWED_HOSTS` like this:

```
ALLOWED_HOSTS=['161.74.26.36','server.sse.asclepios']
```

This will not work, as explained [here](https://github.com/UoW-CPC/Asclepios-TrustedAuthority/issues/4)

It looks like as a quick fix you have hardcoded the value to a wildcard [in `settings.py`](https://github.com/UoW-CPC/Asclepios-Server/blob/master/SSEServer/settings.py#L29)

This is not good as by including the `ALLOWED_HOSTS` in the `.env` files and the deployment manual, you create the illusion of security where there is none.

You can read more about the security issues that arise when you do not properly configure `ALLOWED_HOSTS` [here](https://www.djangoproject.com/weblog/2013/feb/19/security/#s-issue-host-header-poisoning)

**Comment by hvandang** [comment]
I updated ALLOWED_HOSTS in "deloy.env" into correct format (ALLOWED_HOSTS="161.74.26.36 server.sse.asclepios"), and changed settings.py to retrieve value from environment variable

**Comment by jmz-b** [comment]
@hvandang 

you still need to modify this line to `os.getenv('ALLOWED_HOSTS').split(' ')` to make it a list

https://github.com/UoW-CPC/Asclepios-Server/blob/a2f4d99fc1dc3ad6dbcc407b70bd915cece1b89b/SSEServer/settings.py#L29
