### ISSUE TITLE
django configured to use sqlite database

### ISSUE THREAD

**Issue by jmz-b** [UoW-CPC/Asclepios-Server#8]
[This recent change](https://github.com/UoW-CPC/Asclepios-Server/commit/1271e5309807a563d06ad2e54ba4bf9d532ad655) switched the database backend to sqlite in `settings.py`. 

Could we please change it back to using postgres by default so I don't have to overwrite the settings file before deployment?

Or at maybe provide a way to select the database provider with an environment variable?

**Comment by hvandang** [comment]
I've changed back to postgres. Apart from that, for version 0.2, there are 2 tags: 0.2_postgres, 0.2_mysql for the two different databases.

**Comment by jmz-b** [comment]
Thank you!

**Comment by jmz-b** [comment]
@hvandang Will you create `postgres` and `mysql` tags for the `uowcpc/asclepios-server` and `uowcpc/asclepios-ta` docker images as well?

**Comment by hvandang** [comment]
@jmz-b Do you mean master branch? I am planning to keep only postgres in the master branch. Would you also need mysql tag for master branch?

**Comment by jmz-b** [comment]
@hvandang no I only need postgres so don't worry about it

**Comment by hvandang** [comment]
@jmz-b whenever you want to play with mysql, you can use the template files in source code:
cp template_Dockerfile_mysql Dockerfile
cp template_requirements_mysql.txt requirements.txt
cp template_entrypoint_mysql.sh entrypoint.sh
cp template_settings_mysql.py SSEServer/settings.py
